### ISSUE TITLE
Назва файлу компілятора українською

### ISSUE THREAD

**Issue by kant2002** [YuriyLisovskiy/borsch-lang#39]
Зробіть будь ласка ім’я файла компілятора українською `борщ` і нехай `borsch` буде аліасом до українського файла. Це допоможе робити в терміналі цілком українською і наприклад мати файл з українською назвою. Наприклад: `борщ змійка.борщ`

**Comment by YuriyLisovskiy** [comment]
Зробив навпаки – додав alias `борщ` для файла `borsch`.
